services:
  - type: web
    name: mcp-cv-rag-server
    runtime: docker
    plan: free
    region: oregon # or your preferred region
    healthCheckPath: /health
    buildCommand: "" # Docker handles the build
    startCommand: "" # Docker handles the start
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Set this manually in Render dashboard for security
      - key: EMAIL_USER
        sync: false # Set this manually in Render dashboard
      - key: EMAIL_PASSWORD
        sync: false # Set this manually in Render dashboard (Gmail App Password)
      - key: PORT
        value: 10000 # Render's default port
      - key: CORS_ORIGINS
        value: "*" # Configure based on your frontend domains
      - key: PYTHONUNBUFFERED
        value: "1" # Ensure logs are shown in real-time
    autoDeploy: true
    disk:
      name: mcp-data
      mountPath: /app/DB
      sizeGB: 1 # Small disk for vector database storage
