services:
  - type: web
    name: mcp-cv-rag
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
